---
# Experiment to bypass token generation in Headlamp, combined with oauth2 could provide some security
# WARN - not for production use ...
# Mostly generate By AI !!!!!!
# You milage might very for TLS/Ingress
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-admin-proxy
  namespace: headlamp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin-proxy-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: headlamp-admin-proxy
    namespace: headlamp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: headlamp-proxy-config
  namespace: headlamp
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }
    
    http {
        access_log /dev/stdout;
        error_log /dev/stderr;

        server {
            listen 80;
            
            location / {
                proxy_pass http://headlamp:80;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /clusters/main/set-token {
                client_body_buffer_size 128k;
                
                access_by_lua_block {
                    if ngx.req.get_method() == "POST" then
                        ngx.req.read_body()
                        
                        local f = io.open("/var/run/secrets/kubernetes.io/serviceaccount/token", "r")
                        if f then
                            local jwt = f:read("*a")
                            f:close()
                            
                            local cjson = require "cjson"
                            local payload = { token = jwt }
                            local new_body = cjson.encode(payload)
                            
                            ngx.req.set_body_data(new_body)
                            -- Need to update Content-Length or the receiving server might get confused/cutoff
                            -- Nginx usually handles it if we proxy_pass, but set_body_data might be tricky with headers.
                            -- OpenResty docs say ngx.req.set_body_data changes the request body in memory. 
                            -- Content-Length header is NOT automatically updated by set_body_data, we must do it.
                            ngx.req.set_header("Content-Length", #new_body)
                        else
                           ngx.log(ngx.ERR, "Could not open token file")
                        end
                    end
                }
                
                proxy_pass http://headlamp:80;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp-auth-proxy
  namespace: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headlamp-auth-proxy
  template:
    metadata:
      labels:
        app: headlamp-auth-proxy
    spec:
      serviceAccountName: headlamp-admin-proxy
      containers:
        - name: nginx
          image: openresty/openresty:alpine
          volumeMounts:
            - name: config
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config
          configMap:
            name: headlamp-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: headlamp-auth-proxy
  namespace: headlamp
spec:
  selector:
    app: headlamp-auth-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp-proxy
  namespace: headlamp
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - headlamp.DOMAIN
      secretName: headlamp-tls
  rules:
    - host: headlamp.DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headlamp-auth-proxy
                port:
                  number: 80
